FROM python:latest

WORKDIR /app

COPY . .

RUN pip install -U pip && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install gunicorn && \
    pip install wsgiserver

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app"]